server:
    port: 8080

session:
    expiration:
        duration: 10080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5430/bank
        username: bank
        password: bank
    flyway:
        enabled: true
        locations:
            - classpath:db/migration