version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    hostname: database
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=bank
      - POSTGRES_PASSWORD=bank
    ports:
      - "5430:5432"